// !!!IMPORTANT ONLY UPPERCASE!!!
// !!!IMPORTANT ONLY UPPERCASE!!!
// !!!IMPORTANT ONLY UPPERCASE!!!
// !!!IMPORTANT ONLY UPPERCASE!!!
// !!!IMPORTANT ONLY UPPERCASE!!!
// !!!IMPORTANT ONLY UPPERCASE!!!
// !!!IMPORTANT ONLY UPPERCASE!!!
// !!!IMPORTANT ONLY UPPERCASE!!!


export default [
  "PRO_Z22_MISJA",
  "PRO_UPO_W23_KWIECIEN",
  "PRO_UPO_W23_KWIECIEN_NEW",
  "ITME_105",
  "PRO_Z23_1PROCENT35",
  "PRO_Z23_1PROCENT37",
  "PRO_Z23_1PROCENT15_2",
  "PRO_W23_SPOTKANIE"
];
